export const sharedStyles = {
  card: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-card)",
    borderRadius: 16,
    padding: 24,
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-secondary)",
    marginBottom: 16,
  },
  
  input: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: 10,
    border: "1px solid var(--border-input)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
  },
  select: {
    padding: "9px 14px",
    borderRadius: 10,
    border: "1px solid var(--border-input)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 13,
  },
  btn: (variant = "primary") => ({
    padding: "9px 18px",
    borderRadius: 10,
    border: "none",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    transition: "all 0.2s",
    background: variant === "primary" ? "#f59e0b" : "var(--toggle-bg)",
    color: variant === "primary" ? "#000" : "var(--text-primary)",
  }),
  th: {
    padding: "10px 14px",
    textAlign: "left",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-secondary)",
    borderBottom: "1px solid var(--border-subtle)",
    cursor: "pointer",
    userSelect: "none",
    whiteSpace: "nowrap",
  },
  td: {
    padding: "13px 14px",
    fontSize: 13,
    color: "var(--text-body)",
    borderBottom: "1px solid var(--border-row)",
  },
};

